// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4gfbeQlJ2s0ppXg--TzyLVQvHvJ0twUM',
    appId: '1:426701508169:web:6288b8b0fe6a1694853998',
    messagingSenderId: '426701508169',
    projectId: 'chat-app-b7f6c',
    authDomain: 'chat-app-b7f6c.firebaseapp.com',
    storageBucket: 'chat-app-b7f6c.appspot.com',
    measurementId: 'G-QWSP8NMR17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvUUkVDfUkeN6pifXr_NNKIE1HV4_exsw',
    appId: '1:426701508169:android:f7355c937c1cb1c8853998',
    messagingSenderId: '426701508169',
    projectId: 'chat-app-b7f6c',
    storageBucket: 'chat-app-b7f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAYmHz36GQ82GccFLlORmGsLgckrcJ-ks',
    appId: '1:426701508169:ios:cb1c0c7d9fde12e3853998',
    messagingSenderId: '426701508169',
    projectId: 'chat-app-b7f6c',
    storageBucket: 'chat-app-b7f6c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAYmHz36GQ82GccFLlORmGsLgckrcJ-ks',
    appId: '1:426701508169:ios:f3593780d2854041853998',
    messagingSenderId: '426701508169',
    projectId: 'chat-app-b7f6c',
    storageBucket: 'chat-app-b7f6c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
